Repository wemake-services/wemake-python-styleguide, pull requests merged in 2021-10, with the labels that each got.

#2203 Addressed review from @sindresorhus
  CHANGELOG.md
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#2206 Update CHANGELOG.md
  CHANGELOG.md
Labels: hacktoberfest-accepted

#2207 Do not raise reassignment violation over unary operation on the same variable
  tests/test_visitors/test_ast/test_naming/test_variable_self_reassignment.py
  wemake_python_styleguide/violations/best_practices.py
  wemake_python_styleguide/visitors/ast/naming/variables.py
Labels: bug, Hacktoberfest, hacktoberfest-accepted

#2212 Did some Grammar related changes
  README.md
Labels: hacktoberfest-accepted
